name: Release
on:
    pull_request:
        types:
            - closed
jobs:
    release:
        runs-on: ubuntu-latest
        if:  startsWith(github.head_ref, 'chore/version-bump-')
        permissions:
          contents: write
          pull-requests: write
          issues: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.11

            - name: Install Poetry
              run: pip install poetry

            - name: read the version from pyproject.toml
              id: read_version
              run: echo VERSION=$(poetry version -s) >> "$GITHUB_OUTPUT"
                
            - name: Build and publish
              run: |
                poetry install --no-dev
                poetry build
                # poetry publish --build --no-interaction

            - name: Create a release on GitHub
              run: gh release create ${{ steps.read_version.outputs.VERSION }} dist/* --title "Release ${{ steps.read_version.outputs.VERSION }}" --notes "Release ${{ steps.read_version.outputs.VERSION }}"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
