name: Release
on:
    pull_request:
        types: [closed]
        branches:
            - chore/version-bump-*

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
          contents: write
          pull-requests: write
          issues: write

        steps:
            - name: Build and publish
              run: |
                poetry install --no-dev
                poetry build
                # poetry publish

            - name: Create a release on GitHub
              run: gh release create ${{ steps.bump_version.outputs.VERSION }} dist/* --title "Release ${{ steps.bump_version.outputs.VERSION }}" --notes "Release ${{ steps.bump_version.outputs.VERSION }}"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
